---
- shell:        if ! grep -q AllowUsers /etc/ssh/sshd_config; then echo AllowUsers ansible >> /etc/ssh/sshd_config && echo changed; fi
  register:     allow_users_shell_result
  changed_when: allow_users_shell_result.stdout.find('changed') != -1

- replace:
    dest:       /etc/ssh/sshd_config
    regexp:     '^(AllowUsers(?!.*\b{{ item }}\b)) *(.*)$'
    replace:    '\1                      \2 {{ item }}'
  with_items:   "{{ allow_users }}"
  register:     allow_users_result

- service:
    name:       'ssh'
    state:      'restarted'
  when:         allow_users_result.changed
