---
- name:                 'purge packages'
  apt:
    name:               "{{ item }}"
    state:              'absent'
    purge:              'yes'
#    autoremove:         'yes'
  with_items:           "{{ apt_purge_packages }}"
  register:             apt_purge_packages_result
