---
- command:              "{{ item.command }}"
  become:               True
  become_method:        'sudo'
  become_user:          "{{ item.user|default('root') }}"
  args:
    chdir:              "{{ item.chdir|default('/') }}"
    creates:            "{{ item.creates|default('/does/not/create/anything') }}"
  with_items:           "{{ commands }}"
  register:             commands_result
  changed_when:         "{{ item.changed_when|default(commands_result.changed) }}"
