---
- name:                 'set database password(s)'
  mysql_user:
    name:               "{{ item.user }}"
    state:              'present'
    password:           "{{ item.password }}"
    login_user:         'root'
    login_unix_socket:  '/var/run/mysqld/mysqld.sock'
  no_log:               True
  with_items:           "{{ database_passwords }}"
  register:             database_passwords_result
