---
- name:                 'create database(s)'
  mysql_db:
    name:               "{{ item.name }}"
    state:              'present'
    collation:          "{{ item.collation|default('') }}"
    encoding:           "{{ item.encoding|default('') }}"
    login_user:         'root'
    login_unix_socket:  '/var/run/mysqld/mysqld.sock'
  register:             databases_result
  with_items:           "{{ databases}}"

- name:                 'set database privileges'
  mysql_user:
    name:               "{{ item.owner }}"
    append_privs:       True
    priv:               "{{ item.name }}.*:ALL"
    login_user:         'root'
    login_unix_socket:  '/var/run/mysqld/mysqld.sock'
  when:                 item.owner is defined
  with_items:           "{{ databases}}"
