---
# If this task installs repos, the automatic update system needs to find and
# update them.  Disable until that is ready.

- git:
    repo:               "{{ item.repo }}"
    dest:               "{{ item.dest }}"
  # install == changed; update == unchanged
  changed_when:         "'null' == git_repos_result.before"
  with_items:           "{{ git_repos }}"
  register:             git_repos_result
