---
- name:                 'check for directory'
  stat:
    path:               '../files/conf/homedirs/common/common/'
  delegate_to:          localhost
  become:               'no'
  register:             homedir_common_check_result
- name:                 'home directory contents, common'
  copy:
    src:                '../files/conf/homedirs/common/common/'
    dest:               "~{{ homedir_user }}/"
  register:             homedir_common_result 
  when:                 homedir_common_check_result.stat.exists
- name:                 'check for directory'
  stat:
    path:               '../../sensitive_ansible/files/conf/homedirs/common/common/'
  delegate_to:          localhost
  become:               'no'
  register:             homedir_common_sensitive_check_result
- name:                 'home directory contents, common, sensitive'
  copy:
    src:                '../../sensitive_ansible/files/conf/homedirs/common/common/'
    dest:               "~{{ homedir_user }}/"
  register:             homedir_common_sensitive_result 
  when:                 homedir_common_sensitive_check_result.stat.exists
- name:                 'check for directory'
  stat:
    path:               "../files/conf/homedirs/{{ homedir_user }}/common/"
  delegate_to:          localhost
  become:               'no'
  register:             homedir_by_user_check_result
- name:                 'home directory contents, by user'
  copy:
    src:                "../files/conf/homedirs/{{ homedir_user }}/common/"
    dest:               "~{{ homedir_user }}/"
  register:             homedir_by_user_result
  when:                 homedir_by_user_check_result.stat.exists
- name:                 'check for directory'
  stat:
    path:               "../../sensitive_ansible/files/conf/homedirs/{{ homedir_user }}/common/"
  delegate_to:          localhost
  become:               'no'
  register:             homedir_by_user_sensitive_check_result 
- name:                 'home directory contents, by user, sensitive'
  copy:
    src:                "../../sensitive_ansible/files/conf/homedirs/{{ homedir_user }}/common/"
    dest:               "~{{ homedir_user }}/"
  register:             homedir_by_user_sensitive_result
  when:                 homedir_by_user_sensitive_check_result.stat.exists
- name:                 'check for directory'
  stat:
    path:               "../files/conf/homedirs/{{ homedir_user }}/{{ inventory_hostname }}/"
  delegate_to:          localhost
  become:               'no'
  register:             homedir_by_user_at_host_check_result
- name:                 'home directory contents, by user and host'
  copy:
    src:                "../files/conf/homedirs/{{ homedir_user }}/{{ inventory_hostname }}/"
    dest:               "~{{ homedir_user }}/"
  register:             homedir_by_user_at_host_result
  when:                 homedir_by_user_at_host_check_result.stat.exists
- name:                 'check for directory'
  stat:
    path:               "../../sensitive_ansible/files/conf/homedirs/{{ homedir_user }}/{{ inventory_hostname }}/"
  delegate_to:          localhost
  become:               'no'
  register:             homedir_by_user_at_host_sensitive_check_result 
- name:                 'home directory contents, by user and host, sensitive'
  copy:
    src:                "../../sensitive_ansible/files/conf/homedirs/{{ homedir_user }}/{{ inventory_hostname }}/"
    dest:               "~{{ homedir_user }}/"
  register:             homedir_by_user_at_host_sensitive_result
  when:                 homedir_by_user_at_host_sensitive_check_result.stat.exists
- name:                 'register results'
  command:              /bin/true
  register:             homedir_result
  changed_when:         homedir_common_result.changed
                        or homedir_common_sensitive_result.changed
                        or homedir_by_user_result.changed
                        or homedir_by_user_sensitive_result.changed
                        or homedir_by_user_at_host_result.changed
                        or homedir_by_user_at_host_sensitive_result.changed
