# https://github.com/ansible/ansible/issues/7490
---
- name:                 'unspecified path'
  fail:
    msg:                'You have to set either dest or path when including the initialize_files task.'
  with_items:           "{{ initialize_files }}"
  when:                 item.dest is undefined and item.path is undefined

- name:                 'too many paths specified'
  fail:
    msg:                'Set either dest or path, but not both, when including the initialize_files task.'
  with_items:           "{{ initialize_files }}"
  when:                 item.dest is defined and item.path is defined

- name:                 'initialize files'
  file:
    owner:              "{{ item.owner }}"
    group:              "{{ item.group }}"
    mode:               "{{ item.mode }}"
    state:              'touch'
    path:               "{{ item.path }}"
    modification_time:  'preserve'
    access_time:        'preserve'
  with_items:           "{{ initialize_files }}"
  register:             initialize_files_result
  when:                 item.path is defined

- name:                 'initialize files'
  file:
    owner:              "{{ item.owner }}"
    group:              "{{ item.group }}"
    mode:               "{{ item.mode }}"
    state:              'touch'
    dest:               "{{ item.dest }}"
    modification_time:  'preserve'
    access_time:        'preserve'
  with_items:           "{{ initialize_files }}"
  register:             initialize_files_result
  when:                 item.dest is defined
