---
- file:
    owner:              'root'
    group:              'root'
    mode:               '0755'
    path:               '/usr/local/python-packages/'
    state:              'directory'

- name:                 'install python packages'
  pip:
    name:               "{{ item }}"
    state:              'present'
    virtualenv:         "/usr/local/python-packages/{{ item }}"
  with_items:           "{{ install_python_packages }}"
  register:             install_python_packages_result
