---
- name:                 'install files; ignore results (never show "changed" status)'
  become:               True
  become_user:          'root'
  copy:
    owner:              "{{ item.owner }}"
    group:              "{{ item.group }}"
    mode:               "{{ item.mode }}"
    src:                "{{ item.src }}"
    dest:               "{{ item.dest }}"
  changed_when:         False
  with_items:           "{{ install_files_ignore_result }}"
