---
- name:                 'install files'
  copy:
    owner:              "{{ item.owner|default(item.user) }}"
    group:              "{{ item.group }}"
    mode:               "{{ item.mode }}"
    src:                "{{ item.src }}"
    dest:               "{{ item.dest|default(item.path) }}"
  with_items:           "{{ install_files }}"
  register:             install_files_result
