---
- name:                 'install files'
  become:               True
  become_user:          'root'
  copy:
    owner:              "{{ item.owner }}"
    group:              "{{ item.group }}"
    mode:               "{{ item.mode }}"
    src:                "{{ item.src }}"
    dest:               "{{ item.dest }}"
  with_items:           "{{ install_files }}"
  register:             install_files_result
