---
- name:                 'easy_install pip'
  easy_install: 
    name:               'pip'
  register:             easy_install_pip_result
- name:                 'install python packages'
  pip:
    name:               "{{ install_python_packages }}"
    state:              'present'
  register:             install_python_packages_result

