---
#- name:                 'initialize files'
#  script:               ../files/scripts/initialize_file /etc/ssh/ssh_known_hosts 'root' 'root' '0644'
#  register:             initialize_file_script_result
#  changed_when:         false

- name:                 'initialize files'
  include:              ../tasks/create_files.yml
  vars:
    create_files:
      - path:         '/etc/ssh/ssh_known_hosts'
        owner:        'root'
        group:        'root'
        mode:         '0644'
        state:        'touch'

- file:
    owner:              'root'
    group:              'root'
    mode:               '0644'
    state:              'file'
    path:               '/etc/ssh/ssh_known_hosts'

# These always report change.  I don't know why.
- name:                 'known hosts - short hostname'
  known_hosts:
    path:               "/etc/ssh/ssh_known_hosts"
    name:               "{{ item }}"
    key:                "{{ lookup('file', '../../inventory/hosts/{{ item }}/files/ssh_keys/known_host') }}"
  with_items:           "{{ known_hosts }}"
  changed_when:         false
  register:             known_hosts_short_result
- name:                 'known hosts - long hostname'
  known_hosts:
    path:               "/etc/ssh/ssh_known_hosts"
    name:               "{{ item }}.{{ domain }}"
    key:                "{{ lookup('file', '../../inventory/hosts/{{ item }}/files/ssh_keys/known_host') }}"
  with_items:           "{{ known_hosts }}"
  changed_when:         false
  register:             known_hosts_long_result
- name:                 'known hosts - ip address'
  known_hosts:
    path:               "/etc/ssh/ssh_known_hosts"
    name:               "{{ lookup('dig', '{{ item }}.') }}"
    key:                "{{ lookup('file', '../../inventory/hosts/{{ item }}/files/ssh_keys/known_host') }}"
  with_items:           "{{ known_hosts }}"
  changed_when:         false
  register:             known_hosts_numeric_result
