---
- name:                 'mount'
  mount:
    name:               "{{ volume.name }}"
    fstype:             "{{ volume.fstype }}"
    opts:               "{{ volume.opts }}"
    src:                "{{ volume.src }}"
    state:              "{{ volume.state }}"
  with_items:           "{{ mount }}"
  loop_control:
    loop_var:           'volume'
  register:             mount_result
