---
- name:                 'remove packages'
  apt:
    name:               '{{ remove_packages }}'
    state:              'absent'
    purge:              True
  register:             remove_packages_result
