---
- name:                 'synchronize directories (options specified)'
  synchronize:
    archive:            False
    recursive:          True
    perms:              True
    owner:              False
    group:              False
    times:              False
    # Even with "times" disabled, "checksum" is necessary, or change is always reported.
    checksum:           True
    # WTF; why would I have to specify this?!
    verify_host:        True
    src:                "{{ item.src }}"
    dest:               "{{ item.dest }}"
    delete:             "{{ item.delete }}"
    rsync_opts:         "{{ item.rsync_opts }}"
  with_items:           "{{ sync_dirs }}"
  when:                 item.rsync_opts is defined
  register:             sync_dirs_result

- name:                 'synchronize directories (no options specified)'
  synchronize:
    archive:            False
    recursive:          True
    perms:              True
    times:              False
    owner:              False
    group:              False
    # Even with "times" disabled, "checksum" is necessary, or change is always reported.
    checksum:           True
    # WTF; why would I have to specify this?!
    verify_host:        True
    src:                "{{ item.src }}"
    dest:               "{{ item.dest }}"
    delete:             "{{ item.delete }}"
  with_items:           "{{ sync_dirs }}"
  when:                 item.rsync_opts is not defined
  register:             sync_dirs_result
