---
- name:                 'template files'
  become:               True
  become_user:          'root'
  template:
    owner:              "{{ item.owner|default(item.user) }}"
    group:              "{{ item.group }}"
    mode:               "{{ item.mode }}"
    src:                "{{ item.src }}"
    dest:               "{{ item.dest }}"
  with_items:           "{{ template_files }}"
  register:             template_files_result
