---
- name:                 "Deploy!"
  connection:           "{{ connection|default('ssh') }}"
  remote_user:          "{{ remote_user|default('ansible') }}"
  become:               'yes'
  become_method:        'sudo'
  gather_facts:         "{{ gather_facts|default('no') }}"
  hosts:                "{{ target_hosts }}"
  tasks:
    - include_role:
        name:           "{{ target_role }}"
      with_items:       "{{ target_roles }}"
      loop_control:
        loop_var:       'target_role'
